name: Shutdown GCP Instance
description: Shutdown a GCP instance

inputs:
  machine_name:
    description: The name of the machine to shutdown
    required: true
  zone:
    description: The zone of the machine to shutdown
    required: true
  project:
    description: The project to shutdown the machine in
    required: true
  service_account:
    description: The service account to use for the shutdown
    required: true
  workload_identity_provider:
    description: The workload identity provider to use for the shutdown
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup GCloud
      uses: ./.github/actions/setup_gcloud
      with:
        gcp_project_id: ${{ inputs.project }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        gcp_service_account_email: ${{ inputs.service_account }}

    - name: Shutdown Instance
      shell: bash
      run: |
        gcloud compute instances delete ${inputs.machine_name} --zone=${inputs.zone}